---
# tasks file for common_standalone
- name: Install utilities
  become: true
  apt: pkg={{ item }} state=latest force=yes
  with_items:
    - htop
  tags: ami

- name: Install pip packages
  become: true
  pip: name={{ item }} state=latest
  with_items:
    - paramiko-ng
    - scp
    # - jupyter
  tags: [ami, extras]
