---
- name: config Hadoop core-site.xml
  # become: true
  template: src=conf/core-site.xml.j2 dest="{{ hadoop_root }}/etc/hadoop/core-site.xml"
  when: hostvars.localhost.spark_master is defined

- name: config Hadoop core-site.xml
  # become: true
  template: src=conf/core-site-local.xml.j2 dest="{{ hadoop_root }}/etc/hadoop/core-site.xml"
  when: hostvars.localhost.spark_master is not defined

- name: config Hadoop mapred-site.xml
  # become: true
  template: src=conf/mapred-site-local.xml.j2 dest="{{ hadoop_root }}/etc/hadoop/mapred-site.xml"
  when: hostvars.localhost.spark_master is not defined

- name: config Hadoop yarn-site.xml
  # become: true
  template: src=conf/yarn-site-local.xml.j2 dest="{{ hadoop_root }}/etc/hadoop/yarn-site.xml"
  when: hostvars.localhost.spark_master is not defined
  tags: yarn

- name: config Hadoop master
  # become: true
  template: src=conf/masters.j2 dest="{{ hadoop_root }}/etc/hadoop/masters"
  when: hostvars.localhost.spark_master is defined

- name: config Hadoop master
  # become: true
  template: src=conf/masters-local.j2 dest="{{ hadoop_root }}/etc/hadoop/masters"
  when: hostvars.localhost.spark_master is not defined

- name: config Hadoop slaves
  # become: true
  template: src=conf/slaves.j2 dest="{{ hadoop_root }}/etc/hadoop/slaves"
  when: hostvars.localhost.spark_master is defined

- name: config Hadoop slaves
  # become: true
  template: src=conf/slaves-local.j2 dest="{{ hadoop_root }}/etc/hadoop/slaves"
  when: hostvars.localhost.spark_master is not defined

- name: attempt to stop Hadoop cluster
  # become: true
  shell: "{{ hadoop_root }}/sbin/stop-all.sh"
  tags: run
  when: inventory_hostname in groups['tag_ds_role_spark_master']

- name: format Hadoop namenode
  # become: true
  command: echo 'Y' | "{{ hadoop_root }}/bin/hdfs namenode -format"
  when: inventory_hostname in groups['tag_ds_role_spark_master']

- name: format Hadoop namenode
  # become: true
  shell: "echo 'Y' | {{ hadoop_root }}/bin/hdfs namenode -format" 
  when: inventory_hostname in groups['tag_ds_role_spark_master']

######## YARN Related stuff (Separate with a tag)
- name: Add spark to path
  lineinfile: path=~/.profile line='PATH={{ spark_root }}/bin:$PATH'
  tags: yarn

- name: Add hadoop lib to LD PATH
  lineinfile: path=~/.profile line='export LD_LIBRARY_PATH={{ hadoop_root }}/lib/native:$LD_LIBRARY_PATH'
  tags: yarn

- name: Add Spark home environment variable
  lineinfile: path=~/.profile line='export SPARK_HOME={{ spark_root }}'
  tags: yarn

- name: Add Hadoop conf environment variable
  lineinfile: path=~/.profile line='export HADOOP_CONF_DIR={{ hadoop_root }}/etc/hadoop'
  tags: yarn
########
