- name: Install Python
  hosts: tag_ds_tech_spark
  gather_facts: False
  tasks:
    - name: Install Python
      shell: apt-get install python -y
      become: yes

- name: Install Java
  hosts: tag_ds_tech_spark
  roles:
#    - role: ansiblebit.oracle-java
#      oracle_java_deb_package: 'oracle-java8-installer'
    - role: mrlesmithjr.openjdk
      openjdk_version: 8
  tags: java

- name: Set ssh config
  hosts: all
  tasks:
    - name: Copy ssh config
      copy: src=config dest=~/.ssh/config
      #become: yes

- name: Install spark
  hosts: tag_ds_tech_spark
  roles:
  - common
  - spark_common
  tags: spark


- name: Config spark master
  hosts: tag_ds_role_spark_master
  roles:
  - common_standalone
  - spark_master
  tags: spark

- name: Install Hadoop slaves
  hosts: tag_ds_role_spark_slave
  roles:
  - { role: setup_hadoop, hadoop_type_of_node: slave}
  tags: hadoop

- name: Install Hadoop master
  hosts: tag_ds_role_spark_master
  roles:
  - { role: setup_hadoop, hadoop_type_of_node: master}
  tags: hadoop
