---
region: us-east-2
instance_type: m5.large
master_instance_type: m5.large
slave_count: 2
ec2_key_pair: bilal-us-east

private_key_file : ~/Downloads/bilal-us-east.pem.txt
spot_price: 0.20
# ubuntu_image_ami: ami-06f2f779464715dc5
ubuntu_image_ami: ami-08cec7c429219e339
ec2_volume_size: 40
ec2_master_volume_size: 20

instance_profile_arn: EC2_S3_FULL_ACCESS

boto_profile: default
remote_user: ubuntu

spark_download_url: https://www-eu.apache.org/dist/spark/spark-2.4.4/spark-2.4.4-bin-hadoop2.7.tgz
spark_version: 2.4.4-bin-hadoop2.7
spark_root: /opt/spark
# spark_worker_port: 37700
# spark_worker_port_end: 37800

hadoop_download_url: https://archive.apache.org/dist/hadoop/common/hadoop-2.7.7/hadoop-2.7.7.tar.gz
#hadoop_download_url: http://www-us.apache.org/dist/hadoop/common/hadoop-2.7.7/hadoop-2.7.7.tar.gz
hadoop_version: 2.7.7
hadoop_root: /opt/hadoop

## Memory settings for YARN containers
nodemanager_memory: 30000
scheduler_max_allocation: 30000
###

hbase_download_url: http://www-us.apache.org/dist/hbase/stable/hbase-1.2.2-bin.tar.gz
hbase_version: 1.2.2
hbase_root: /opt/hbase

inventory_dir: /etc/ansible/ec2.py

jdk_version: 8
