---
# tasks file for spark_common

- name: download Spark pre-built package
  become: yes
  get_url: url={{ spark_download_url }} dest="/tmp/spark-{{ spark_version }}.tgz"

- name: extract Spark archive
  become: yes
  unarchive: copy=no src="/tmp/spark-{{ spark_version }}.tgz" dest=/opt/

- name: create link to Spark directory
  become: yes
  file: src=/opt/spark-{{ spark_version }} dest={{ spark_root }} state=link

- name: configure Spark to run in standalone deploy mode
  become: yes
  template: src=conf/spark-env.sh.j2 dest={{ spark_root }}/conf/spark-env.sh mode="u=rwx,g=rx,o=rx"
  tags: config_spark
