---
# tasks file for hbase
- name: download Hbase pre-built package
  become: true
  get_url: url={{ hbase_download_url }} dest="/tmp/hbase-{{ hbase_version }}.tgz"

- name: extract Hbase archive
  become: true
  unarchive: copy=no src="/tmp/hbase-{{ hbase_version }}.tgz" dest=/opt/

- name: create link to Hbase directory
  become: true
  file: src=/opt/hbase-{{ hbase_version }} dest={{ hbase_root }} state=link

- name: config Hbase env
  become: true
  template: src=conf/hbase-env.sh.j2 dest={{ hbase_root }}/conf/hbase-env.sh mode="u=rwx,g=rx,o=rx"

- name: config Hbase hbase-site.xml
  become: true
  template: src=conf/hbase-site.xml.j2 dest="{{ hbase_root }}/conf/hbase-site.xml" owner=root group=root

- name: config Hbase regionservers
  become: true
  template: src=conf/regionservers.j2 dest="{{ hbase_root }}/conf/regionservers" owner=root group=root

- name: attempt to start Hbasse cluster
  become: true
  shell: "{{ hbase_root }}/bin/start-hbase.sh"
  tags: run
  when: "hbase_type_of_node == 'master'"
