- name: Install essentials
  become: true
  apt: pkg={{ item }} state=installed update_cache=yes
  with_items:
    - build-essential
    - wget
    - tar
    - gzip
    - libffi-dev
    - libssl-dev
    - python
    - python-dev
    - python-pip
    - libblas-dev 
    - liblapack-dev 
    - libatlas-base-dev 
    - gfortran
    - python3

- name: Install pip packages
  become: true
  pip: name={{ item }} state=latest
  with_items:
    - setuptools
    - numpy
    - pandas
    - numexpr
    - urllib3
    - pyOpenSSL
    - ndg-httpsclient
    - pyasn1
