- name: set timezone to ICT
  become: true
  copy:
    content: "Asia/Ho_Chi_Minh\n"
    dest: /etc/timezone
  notify: restart cron

- name: update tzdata
  become: true
  command: "/usr/sbin/dpkg-reconfigure --frontend noninteractive tzdata"
  changed_when: false
